from datetime import date
from decimal import Decimal

from pydantic import BaseModel


class OrderLine(BaseModel):
    """Order line. Mirrors the `order_lines` table.

    `description`, `unit_of_measure` and `unit_price` are COPIED from the article
    when the order is written, not read from the catalogue with a join: when the
    price list changes, orders already placed must stay as they were. An order is
    a historical document, not a view over current data.
    """

    id: int
    order_id: int
    line_no: int

    article_code: str
    description: str
    unit_of_measure: str
    unit_price: Decimal

    quantity: int
    # Column generated by Postgres (quantity * unit_price): read-only.
    line_total: Decimal

    requested_date: date | None = None

    def to_prompt(self):
        return f"article:{self.article_code} - {self.description},qty:{self.quantity}"
